### ISSUE TITLE
[Question] How do you add the cert to SQ?

### ISSUE THREAD

**Issue by jakob1379** [heyValdemar/sonarqube-traefik-letsencrypt-docker-compose#2]
I am trying to make the same setup and stumbled upon your repo after getting an issue where SQ need the cert from traefik for sonar-scanner to function properly. Can you explain what you did?

**Comment by heyvaldemar** [comment]
hey @jakob1379, you can reach me and other IT guys on [Discord](https://discord.gg/AJQGCCBcqf). It will be faster and more effective than here.

Have a great day!
